id: universal
title: Universal development corpus
description: Freely available corpus to use in development
mode:
  - name: default
within:
  - label:
      eng: sentence
    value: sentence
  - label:
      eng: text
    value: text
  - label:
      eng: corpus
    value: corpus
context:
  - label:
      eng: 1 sentence
    value: 1 sentence
  - label:
      eng: 1 text
    value: 1 text
  - label:
      eng: 1 corpus
    value: 1 corpus
